### ISSUE TITLE
Update needed for 24.05

### ISSUE THREAD

**Issue by esthermel** [bywatersolutions/koha-plugin-csv2marc#34]
To replicate:

1. Configure the plugin with:

020:
  - subfield: a
    column: 1
100:
  - subfield: a
    column: 3
245:
  - subfield: a
    column: 2

2. Hit save

Receive this error:
Programming error - No CSRF token passed for POST

**Comment by kidclamp** [comment]
Resolved by 1f8dc2a6a54956adac7f2dcb699c1e2f5571caf
